### ISSUE TITLE
Highlighting numeric literals

### ISSUE THREAD

**Issue by nickjmeyer** [ludwigpacifici/modern-cpp-font-lock#10]
First off, I should say, this has been a really helpful package.  Really nice to have the improved highlighting.  Makes editing that much easier!

When there are numerical characters in a function name or variable name, if they follow an underscore, start with zero, and have at least one additional digit then they are highlighted as a literal.

![image](https://cloud.githubusercontent.com/assets/9648755/23129957/97428dfc-f752-11e6-953c-690f1dfad71c.png)

You can see that it doesn't happen without the underscore.  Also, if it is just a zero or if there is no zero then it is also okay.

**Comment by ludwigpacifici** [comment]
Thanks, I am glad it's helpful to you :-)

Indeed, it is an issue with `modern-cpp-font-lock`. The bug comes from the [octal literals](http://en.cppreference.com/w/cpp/language/integer_literal) highlight.

> octal-literal is the digit zero (0) followed by zero or more octal digits (0, 1, 2, 3, 4, 5, 6, 7)

I let you know when a fix is ready.

**Comment by nickjmeyer** [comment]
Great!  Thanks!!  Really appreciate it.

**Comment by ludwigpacifici** [comment]
Can you checkout [issue-10](https://github.com/ludwigpacifici/modern-cpp-font-lock/tree/issue-10) and let me know if the fix is good for you?

**Comment by nickjmeyer** [comment]
Looks great!  Here is proof.  This is in `text-mode` with `mc++fl`.  It also works with `c++-mode`, but I left it in `text-mode` to be consistent with the above picture.

![image](https://cloud.githubusercontent.com/assets/9648755/23276715/6250e57e-f9d9-11e6-9686-b7cfc7a976c6.png)

I looked at the diff.  Looks like all you had to add was `_` to the exclusion regex?

Thanks for the fix!

**Comment by ludwigpacifici** [comment]
Thank you for your checks. Yes the fix was small.

It should be available on Melpa in few days.
