### ISSUE TITLE
Integration with RTags

### ISSUE THREAD

**Issue by nickjmeyer** [ludwigpacifici/modern-cpp-font-lock#12]
Hi Ludwig, I'm back again!

I just saw this thread Andersbakken/rtags#677 and am really curious to know if there has been any progress to integrate `modern-cpp-font-lock` and `rtags`.  This would be a fantastic feature!

**Comment by ludwigpacifici** [comment]
Hello again @nickjmeyer! 

Thanks for your interest, but I will disappoint you because I have not worked on it yet. I need:

* understand how `rtags` work
* Internet (I am moving home)
* and time.

I might have a look in few months.

**Comment by nickjmeyer** [comment]
Always so many things to do!

My experience with Elisp is very minimal, but I'd be interested in helping out if there is room for collaboration.  Similar to you, I won't be able to spend time figuring things out for a few months.  But in a few months I'll check back and maybe we can put something together!

**Comment by ludwigpacifici** [comment]
Yes, it seems a good idea. Talk to you soon.
