### ISSUE TITLE
Modern C++ indentation?

### ISSUE THREAD

**Issue by WarpRulez** [ludwigpacifici/modern-cpp-font-lock#13]
I am completely tired of Emacs messing up auto-indentation with some of the modern C++ features, such as strongly-typed enums (ie. "enum class ..."). It's highly annoying. Therefore I was hoping that this font-lock would fix those issues, but does not.

Would it be possible to fix the indentation problems that the current official cc-mode has?

**Comment by ludwigpacifici** [comment]
Hello @WarpRulez 

I use [clang-format](https://clang.llvm.org/docs/ClangFormat.html). It can be integrated in Emacs  [manually](https://clang.llvm.org/docs/ClangFormat.html#emacs-integration) or via [Melpa](http://melpa.org/#/clang-format). Then, you can bind it. For example:

```
(define-key c++-mode-map (kbd "C-M-<tab>") #'clang-format-region)
```

Finally, you can [customize your code style](https://clang.llvm.org/docs/ClangFormatStyleOptions.html).

**Comment by WarpRulez** [comment]
It turns out that the newest version of Emacs (25.1.1) already fixed the problem. I had an older version. I apologize for the unwarranted issue.

**Comment by ludwigpacifici** [comment]
No worries.
