### ISSUE TITLE
Integer literal font lock

### ISSUE THREAD

**Issue by nickjmeyer** [ludwigpacifici/modern-cpp-font-lock#17]
I'm having some issues with the interger literal when using the single quote.  I grabbed the examples from your test file.  

Here is what I get with modern cpp mode enabled.

![screenshot from 2018-03-10 13-22-12](https://user-images.githubusercontent.com/9648755/37245479-7035a4a0-2466-11e8-97b1-9b9bbbc6868b.png)

Here is what I get with modern cpp mode disabled.

![screenshot from 2018-03-10 13-25-23](https://user-images.githubusercontent.com/9648755/37245488-89d0e1d6-2466-11e8-91ed-6701b6c51260.png)

**Comment by ludwigpacifici** [comment]
Hello @nickjmeyer,

I believe it's the `c++-mode` that broke the integer literal display. Can you double check your version and try to update it to the latest one?

`M-x` `c-version`: Using CC Mode version [5.33.1](http://cc-mode.sourceforge.net/changes-533.php). The change log says it provides a better C++11 support (separators in integer literals).

On a side note, if you look at `integer-literal/test.txt.faceup`, only `auto` will be font-locked (delimited with `«` and `»`). The integer is untouched.

```text
«k:auto» i = 24'847'458'121;
«k:auto» i = 1'000'000;
```

**Comment by nmeyer-argo** [comment]
Looks like the latest is still 5.32.99.  I'll have to manually update it.  I will give it a try this weekend.

**Comment by nickjmeyer** [comment]
Upgrading CC Mode fixed it.  Wish it was easier to upgrade that mode...  Sort of a pain.

**Comment by ludwigpacifici** [comment]
The Emacs master branch is really stable. You can clone the Emacs repository, run `make bootstrap` and `sudo make install` to compile and install the latest Emacs. It runs with `cc-mode` 5.33. Hope this help.
