### ISSUE TITLE
second function argument type is rendered as a variable

### ISSUE THREAD

**Issue by TooChaos** [ludwigpacifici/modern-cpp-font-lock#18]
The function declarations below highlight ABC as a function variable instead of a type
`void foo(std::string&, ABC);`
`void foo(string s, ABC abc)`
However 
`void foo(string&, ABC);`
and
`void foo(std::string, ABC);`
correctly hightlight ABC as a type.

My modern-cpp-font-lock version is 0.1.3 installed from Melpa, emacs version is 24.5.1 the system is emacs Would you please investigate this problem? Thank you!

**Comment by ludwigpacifici** [comment]
Hello @TooChaos
 
Thanks for the issue.

I suspect the built-in `c++-mode` to create this highlight. Can you reproduce the issue by running emacs with no configuration (i.e. `emacs -Q` in the command line)?

**Comment by TooChaos** [comment]
Thank you for quick response @ludwigpacifici !
Indeed I can reproduce it with vanilla emacs as you suggested. Anything we can do to correct it? Thanks again

**Comment by ludwigpacifici** [comment]
Can you check again with Emacs 26.1? It has been released today, and there is a big chance the `c++-mode` was updated.

If you still see the error with the latest version or you cannot upgrade Emacs, then I suggest you to send an email to the maintainer of [cc-mode](http://cc-mode.sourceforge.net/). You can reach him at this address: bug-cc-mode@gnu.org

**Comment by TooChaos** [comment]
It works now with emacs 26.1. Thank you @ludwigpacifici !
