### ISSUE TITLE
clash between modern-c++-font-lock-mode and built-in c++-mode

### ISSUE THREAD

**Issue by alanconway** [ludwigpacifici/modern-cpp-font-lock#19]
Example code: 
`void f() {
  aut s = R"EOF("a)EOF";
}
`
If I set fundamental-mode and enable modern-c++-font-lock-mode then the raw string is highlighted perfectly so the modern fontifying is working. However if I set c++-mode then modern-c++-font-lock-mode then it is highlighted the old C++ way -  it looks like the built-in c++ fontification is over-riding the modern rules.

To reduce uncertainty I ran this with emacs --no-init so no other ealpa packages are loaded:
(load-library "~/.emacs.d/elpa/modern-cpp-font-lock-0.1.3/modern-cpp-font-lock.el")
Using CC Mode version 5.32.99
GNU Emacs 25.3.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.22.26) of 2018-01-12

I can try to debug this but I'd like some hints where to look. I'm familar with elisp programming but not the font-lock stuff specifically.

**Comment by ludwigpacifici** [comment]
Hello @alanconway. Thanks for your bug report.

Do you mind to try again your test case with the emacs 26.1? `cc-mode` was updated with lots of fixes and it's possible the issue is now solved.

**Comment by collinjackson93** [comment]
I was having the same issue and updating emacs to 26.1 resolved the problem for me.

**Comment by alanconway** [comment]
Works perfectly with emacs 26.1, thanks!
