### ISSUE TITLE
Installation from Melpa fails with compilation error

### ISSUE THREAD

**Issue by kluge** [ludwigpacifici/modern-cpp-font-lock#2]
Compiling file /home/[[redacted]]/.emacs.d/elpa/modern-cpp-font-lock-20160527.1440/modern-cpp-font-lock.el at Wed Jun  1 11:43:53 2016
modern-cpp-font-lock.el:129:188:Error: Symbol's function definition is void: modern-c++-string-lenght>

The Github repository seems to have commits after the Melpa date, so I'm not sure if this is still current.

**Comment by ludwigpacifici** [comment]
Hello @kluge 
As of today, `20160527.1440` is the last version. Other commits does not impact `modern-cpp-font-lock.el`.
I can reproduce the error when the package is compiled via Melpa. I'll have a look.

**Comment by ludwigpacifici** [comment]
Should be fixed with the next update of Melpa. Thanks for spotting this!
