### ISSUE TITLE
string literal isn't rendered at all.

### ISSUE THREAD

**Issue by amosbird** [ludwigpacifici/modern-cpp-font-lock#20]
test file   https://github.com/yandex/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp

env:

emacs 27.0.50 (master branch)
centos 7

**Comment by ludwigpacifici** [comment]
Hello @amosbird 

Can you confirm you have the same issue by opening this file with `emacs -Q <path_to_file>`? I did this on my side, and I can see that a sizable part of the file is not highlighted correctly. For information, I used the same version as you.

If you confirm this, then I suggest you to report a bug to [cc-mode](http://cc-mode.sourceforge.net/) at  bug-cc-mode@gnu.org. This package cannot solve bugs of the `c++-mode`.

![font-highlight](https://user-images.githubusercontent.com/923945/43608578-5448bdea-9699-11e8-9b91-057ae13ea202.png)

**Comment by ludwigpacifici** [comment]
I close this issue. The bug is reported to CC Mode and a fix is available. See https://sourceforge.net/p/cc-mode/mailman/message/36429312/
