### ISSUE TITLE
Inclusion in Emacs core

### ISSUE THREAD

**Issue by innerout** [ludwigpacifici/modern-cpp-font-lock#21]
I am opening this issue after seeing the reddit post below. https://www.reddit.com/r/emacs/comments/94j39z/modern_c_font_lock_in_emacs/

Could you make the effort and email the emacs mailing list for your plugin to be included in the Emacs core?

**Comment by ludwigpacifici** [comment]
Hello @innerout,

Thank you for your interest in this package. I will have a look at it.

**Comment by innerout** [comment]
I will leave the issue open for future updates or should i close it?

**Comment by ludwigpacifici** [comment]
Leave it open. I will probably post some update here.

**Comment by ludwigpacifici** [comment]
Discussion can be followed here: https://lists.gnu.org/archive/html/emacs-devel/2018-08/msg00170.html
