### ISSUE TITLE
if constexpr indent

### ISSUE THREAD

**Issue by ShigekiKarita** [ludwigpacifici/modern-cpp-font-lock#22]
From c++ 17, `if constexpr` statement is introduced but its indentation looks collapsed like this.
``` c++
if constexpr (true) {
        f();
    }
```
Maybe your mode does not support indentation. I wonder if you have any solution for this problem (adding keywords or something).

**Comment by ludwigpacifici** [comment]
> I wonder if you have any solution for this problem (adding keywords or something).

Indentation is handle by cc-mode. Have a look at the documentation: [official](https://www.gnu.org/software/emacs/manual/html_node/ccmode/Customizing-Indentation.html) or [emacsWiki](https://www.emacswiki.org/emacs/IndentingC).

[ClangFormat](https://clang.llvm.org/docs/ClangFormat.html#emacs-integration) can replace the default indent and it can be integrated in Emacs.

If you think there is bug, please report it to bug-cc-mode@gnu.org.

**Comment by ShigekiKarita** [comment]
thanks for pointers!
