### ISSUE TITLE
expected to work with GNU Emacs 25.2.2?

### ISSUE THREAD

**Issue by kookjr** [ludwigpacifici/modern-cpp-font-lock#24]
I'm using stock Ubuntu 18.04, which has this version of emacs. When I do the following:

    M-x package-install [RET] modern-cpp-font-lock [RET]

I get this in the Messages buffer.

    Contacting host: melpa.org:80
    package-install-from-archive: http://melpa.org/packages/modern-cpp-font-lock-20180110.2031.el: Not found

**Comment by ludwigpacifici** [comment]
Hello @kookjr ,

The package should be available in Melpa: https://melpa.org/#/modern-cpp-font-lock.

You attempt to load the version `20180110.2031`, and I am not sure Melpa keeps old version of packages. I recommend you to use the latest version: `20190331.1528`.

On how to use Melpa have a look at https://melpa.org/#/getting-started. You might want to ensure your Emacs gets the latest version of Melpa packages by running `M-x package-refresh-contents`.

I hope this help.

**Comment by kookjr** [comment]
Yes, the refresh worked. Thanks!
