### ISSUE TITLE
Font lock for function calls

### ISSUE THREAD

**Issue by hisnawi** [ludwigpacifici/modern-cpp-font-lock#28]
I tried looking int he source code but it doesn't seem function "calls" from inside other functions has an option for a highlight.
is that correct? or did I miss something?
If it is the case, is it possible to add this support? I feel that highlighting function calls in specific helps great deal in understanding any new code.

**Comment by ludwigpacifici** [comment]
Hello,

You are correct there is no support of function calls and it is expected. This packages focuses on the language itself and not the user code.

Maybe you are looking for a tool that jump to definition of a function? Like `ctags`or `lsp-mode`.

**Comment by hisnawi** [comment]
I already have lsp-mode running. 
But I agree, it is not something this package should have.
