### ISSUE TITLE
Hexadecimal digits prefix highlights as keyword

### ISSUE THREAD

**Issue by condy0919** [ludwigpacifici/modern-cpp-font-lock#29]
![image](https://user-images.githubusercontent.com/4024656/80595244-fe826380-8a56-11ea-888c-e50fe8d99847.png)

It can be reproduced using the following `init.el` with `emacs -Q -l init.el`.

```elisp
(require 'package)
(setq package-archives
      '(("gnu"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
        ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")))

(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(use-package modern-cpp-font-lock
  :ensure t
  :hook (c++-mode . modern-c++-font-lock-mode))

(provide 'init)
```

emacs --version

``` text
GNU Emacs 28.0.50
Copyright (C) 2020 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

cc-mode version

```
;; Version: 5.33.1
```

After reading the source, it seems like a feature but a bug.

https://github.com/ludwigpacifici/modern-cpp-font-lock/blob/master/modern-cpp-font-lock.el#L186

**Comment by ludwigpacifici** [comment]
It is expected expected. The goal is to highlight the [prefixes](https://en.cppreference.com/w/cpp/language/integer_literal) `0`, `0b`, `0x`. Why do you think this is a bug?

**Comment by condy0919** [comment]
Other text editors like vim and vs code highlight `0x11` in the same color. It makes more sense.

Would you like to make it customizable?

![vim](https://user-images.githubusercontent.com/4024656/81309674-c95cbd80-90b5-11ea-843a-73a58825789c.png)

![vs code](https://user-images.githubusercontent.com/4024656/81309791-e6918c00-90b5-11ea-9e0e-37b0d22b2785.png)

**Comment by ludwigpacifici** [comment]
The goal is not too be like Vim or Visual Studio Code, but it is too highlight the base prefix as it gives different values for numbers. For example, consider `11`, `0b11`,  `011` and `0x11`, they are all different values.

I am fine to make it customisable. You can raise a PR for it and I'll be happy to review it.
