### ISSUE TITLE
tries to compile/load the test file

### ISSUE THREAD

**Issue by blaenk** [ludwigpacifici/modern-cpp-font-lock#3]
When attempting to install the latest version from MELPA, I get an error because it tries to load faceup.el from `~/.emacs.d/faceup/faceup.el` which AFAIK is because of the recent inclusion of tests. I think perhaps the test files need to be excluded from the MELPA definition for the package?

**Comment by ludwigpacifici** [comment]
Hello @blaenk 

You are right, I was not aware that melpa was loading files by following these default rules:

```
("*.el" "*.el.in" "dir" "*.info" "*.texi" "*.texinfo"
 "doc/dir" "doc/*.info" "doc/*.texi" "doc/*.texinfo"
 (:exclude ".dir-locals.el" "test.el" "tests.el" "*-test.el" "*-tests.el"))
```

I will move the tests so they won't be seen by Melpa and keep a default recipe configuration for Melpa - I want to keep things simple with Melpa as it is not my project.

**Comment by ludwigpacifici** [comment]
It should be fixed when Melpa will refresh the package. I expect to see only `modern-cpp-font-lock.el` and `modern-cpp-font-lock.elc` in the Melpa directory.

**Comment by blaenk** [comment]
Seems to be working, thanks!
